---
title: "Time line plots"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(tidyverse)
```

### Quantities of lobster landed on the East coast

```{r}
eastcoastlandings <- read.csv("LandingsCanada.csv")
eastcoastlandings<- rename(eastcoastlandings, Year= ï..Year, 
                           Landings_MT= Landings.MT.)

figlandings<- ggplot(data=eastcoastlandings, aes(x=Year, y=Landings_MT)) +
  geom_bar(stat="identity", fill="coral2") +
  labs(x= "", y="Volume in metrci tonnes") +
  scale_x_continuous(breaks = seq(1893, 2020, by = 7)) + 
  theme(
    panel.border = element_blank(),  
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    axis.line = element_line(colour = "black")) +
  theme(axis.text.x = element_text(size= 9, angle = 270, hjust = 0.75))
figlandings
```

### Value of exports of lobster

```{r}
nsectiondata<- read.csv("Nsection.csv")
nsectiondata<- rename(nsectiondata, Year= ï..year, 
                           Fresh=fresh.export, Processed=canned.export, Total=total.export)

export<- select(nsectiondata, -2)
exportlong<- gather(export, key = "Type", value="Export value", 2:4)
exportlong <- rename(exportlong, value=`Export value`)

figexport<- ggplot(data=exportlong, aes(x=Year, y=value)) +
  geom_line(aes(color=Type), size=1.5) +
  labs(x= "", y="Value in thousands of dollars", color="") +
  theme(
    panel.border = element_blank(),  
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.position = "bottom") 
figexport
```

### Lobster landings by LFA

```{r}
lfalandings <- read.csv("LandingsLFA.csv")
lfalandingsWide<-   gather(lfalandings, key = "Location", value = "Landings", 2:16)
#if a subset of LFAs to be shown:
subsetlfalandingsWide<- subset(lfalandingsWide, Location!="LFA31A" & Location!="LFA31B")

figlafalandings <- ggplot(data=subsetlfalandingsWide, aes(YR, Landings,  colour=Location)) +
geom_line(size=0.75, alpha=0.7)  +  theme(legend.position="bottom") +
  labs(x = "Year", y="Volume in metric tonnes") +
  theme(axis.text = element_text(size = 12)) +       
  theme(axis.title = element_text(size = 14))  +    
  theme(
    panel.border = element_blank(),  
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    axis.line = element_line(colour = "black"))
figlafalandings
    ```